site_name: Smart-Shell
repo_url: https://github.com/Lusan-sapkota/smart-shell
docs_dir: docs
site_url: https://lusan-sapkota.github.io/smart-shell/
nav:
  - Home: index.md
  - Getting Started:
    - Features: features.md
    - Installation: installation.md
    - Usage: usage.md
    - Uninstall: uninstall.md
  - Documentation:
    - Safety: safety.md
    - API Reference: api.md
    - FAQ: faq.md
  - Development:
    - Development Guide: DEVELOPMENT.md
    - Contributing: contributing.md
  - Project Info:
    - Changelog: CHANGELOG.md
    - Future Changes: futurechanges.md
    - License: license.md
    - Author: author.md
theme:
  name: material
  logo: images/logo.png
  favicon: images/logo.png
  palette:
    - scheme: default
      primary: blue
      accent: orange
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - tables
  - pymdownx.superfences
  - pymdownx.details
plugins:
  - search
  - mkdocstrings
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Lusan-sapkota/smart-shell
    - icon: fontawesome/brands/python
      link: https://www.python.org/
    - icon: fontawesome/solid/globe
      link: https://lusansapkota.com.np/
